const Types = {
    ADDITION: "ADDITION",
    SUBTRACTION: "SUBTRACTION",
    AUTHENTICATION: "AUTHENTICATION",
    USERS: "USERS",
    GET_PHOTOS: "GET_PHOTOS",
    GET_PHOTOS_REQ: "GET_PHOTOS_REQ",
    GET_PHOTOS_REQ_END: "GET_PHOTOS_REQ_END",
};

export default Types